### ISSUE TITLE
Issues with Soil Codelists

### ISSUE THREAD

**Issue by KathiSchleidt** [INSPIRE-MIF/helpdesk-registry#33]
When reviewing the INSPIRE Soil Data Models and Codelists during work for EEA ETC-DI, I noticed two minor issues in the codelists:

**WRB Qualifier Place**
https://inspire.ec.europa.eu/codelist/WRBQualifierPlaceValue
The definition states that this non-extendable codelist shall have the values "prefix" and "suffix". Unfortunately, these values are missing. 
The inclusion of these 2 required concepts has no impact on the IRs (also require exactly these 2 values)

**measure taken stage value**
https://inspire.ec.europa.eu/codelist/MeasureTakenStageValue
This entry currently has the wrong label "measure taken status value". This causes confusion with https://inspire.ec.europa.eu/codelist/MeasureTakenStatusValue, that actually has this name!

**Comment by KathiSchleidt** [comment]
A further issue pertains to the location of the document underpinning the following codelists:
- FAO Horizon Master
- FAO Horizon Subordinate
- FAO Prime

Link references: ftp://ftp.fao.org/agl/agll/docs/guidel_soil_descr.pdf
Should be: http://www.fao.org/3/a-a0541e.pdf

**Comment by jescriu** [comment]
Dear @KathiSchleidt,

Regarding your 1st post:

> When reviewing the INSPIRE Soil Data Models and Codelists during work for EEA ETC-DI, I noticed two minor issues in the codelists:
> 
> WRB Qualifier Place
> https://inspire.ec.europa.eu/codelist/WRBQualifierPlaceValue
> The definition states that this non-extendable codelist shall have the values "prefix" and "suffix". Unfortunately, these values are missing.
> The inclusion of these 2 required concepts has no impact on the IRs (also require exactly these 2 values)
> 
> measure taken stage value
> https://inspire.ec.europa.eu/codelist/MeasureTakenStageValue
> This entry currently has the wrong label "measure taken status value". This causes confusion with https://inspire.ec.europa.eu/codelist/MeasureTakenStatusValue, that actually has this name!

I agree that both requests should be processed and corrected in the INSPIRE Registry as quickly as possible, since they are just correcting lacks / typos.

Regarding your 2nd post:

> A further issue pertains to the location of the document underpinning the following codelists:
> 
>     FAO Horizon Master
>     FAO Horizon Subordinate
>     FAO Prime
> 
> Link references: ftp://ftp.fao.org/agl/agll/docs/guidel_soil_descr.pdf
> Should be: http://www.fao.org/3/a-a0541e.pdf

Exactly the same, since this is just an update of the document location.
For each of these 3 last code lists, would be any way to point to a specific section of the FAO 'Guidelines for Soil Description' (e.g. a bookmark in the document). Probably this will require FAO attention.

Best,
Jordi

**Comment by KathiSchleidt** [comment]
Dear @jescriu, 
On FAO Document location, I fear this is a bit of a moving target from the FAO side - at least I remember having already provided an update for this document a few years ago. Not sure if we can influence the FAO, or just do our best to keep up with current document location.
We have been making progress in digitizing the content of both the FAO and WRB Codelists under Soil (both just reference a PDF, provide page numbers, but no referenceable concepts), the digitized versions are currently being checked by ISRIC. Once these have been validated, we will provide them for import to the Registry.
:)
Kathi

**Comment by jescriu** [comment]
Thank you for you answer, @KathiSchleidt,
At the end, this would not be needed if the code list are included and managed in the INSPIRE Registry in the future.

**Comment by ldesousa** [comment]
Dear all,

in attachment is the list of WRB qualifiers digitised from the 2007 edition document. This list corresponds to the type `WRBQualifierValue` used on the `WRBQualifier` property of the `WRBQualifierGroupType` class. These qualifies match the RSGs already published online by the JRC (also digitised from 2007 edition). Please let me know if you find any errors or need additional information.

[qualifiersWRB.xlsx](https://github.com/INSPIRE-MIF/helpdesk-registry/files/8824057/qualifiersWRB.xlsx)

**Comment by ldesousa** [comment]
Dear all,

attached another batch of code-lists. This time the genetic horizon classifications, as defined in the FAO Guidelines for Soil Description. Also the WRB qualifier place code-list that is still missing. The first sheet identifies the code-lists and provides the long descriptions. Please let me know if something is amiss.

Regards.

[AddicionalCodelistsINSPIRE.xlsx](https://github.com/INSPIRE-MIF/helpdesk-registry/files/8968649/AddicionalCodelistsINSPIRE.xlsx)

**Comment by KathiSchleidt** [comment]
Any progress on this issue? I believe we've clarified the point that these are NOT new codelists or entries, just a digital form suitable for Re3gistry import of the content of the textual documents that were originally referenced (but impossible to provide an xlink to a value in a table in a PDF document)

Any information on why this has been delayed for close to a year now?

**Comment by arantzaetxebarria** [comment]
Dear @KathiSchleidt 

This change proposal has recently been presented and accepted in the 74th MIG-T meeting on 28 April. 
After the 2 weeks objection period given to the MIG, if there are no objections, proposals will start to be introduced in the INSPIRE Registry.

We will keep you updated during the process.

Regards

**Comment by KathiSchleidt** [comment]
@ldesousa can you please confirm that the codelists provided are an exact copy of the original FAO document contents currently cited?

**Comment by ldesousa** [comment]
> @ldesousa can you please confirm that the codelists provided are an exact copy of the original FAO document contents currently cited?

I confirm. These code-lists correspond to the 2007 edition of the Word Reference Base of Soil Resources. This document is currently not on-line.

**Comment by arantzaetxebarria** [comment]
We would like to inform you that most of the change proposals have been successfully published:

Label correction in https://inspire.ec.europa.eu/codelist/MeasureTakenStageValue

Link reference in:
  [FAO Master](https://inspire.ec.europa.eu/document/FaoMaster)
  [FAO Sub](https://inspire.ec.europa.eu/document/FaoSub
  [FAO Prime](https://inspire.ec.europa.eu/document/FaoPrime)

New items for
https://inspire.ec.europa.eu/codelist/WRBQualifierPlaceValue
[FAO Horizon Master](https://inspire.ec.europa.eu/codelist/FAOHorizonMasterValue)
[FAO Horizon Subordinate](https://inspire.ec.europa.eu/codelist/FAOHorizonSubordinateValue)
[FAO Prime](https://inspire.ec.europa.eu/codelist/FAOPrimeValue)

Unfortunately, the new items for [WRBQualifierValue](https://inspire.ec.europa.eu/codelist/WRBQualifierValue), are not visible in the table below the parent, but they are accessible one by one e.g https://inspire.ec.europa.eu/codelist/WRBQualifierValue/Novic
We are trying to solve this problem due to software complications that are not easy to fix.

We apologise for the inconvenience.

Regards

**Comment by KathiSchleidt** [comment]
@arantzaetxebarria MANY THANKS!!! Good things take time :)

On the WRBQualifier Value, any ideas why this one codelist doesn't play nice? Did we do something wrong in the import structure?

**Comment by arantzaetxebarria** [comment]
Dear @KathiSchleidt 

We are working on it, trying to see where the error could be, we think it is a problem in the caching process.
As soon as we have news, we will inform you.

Regards

**Comment by arantzaetxebarria** [comment]
Dear @KathiSchleidt 

I would like to inform you that once the problem affecting this codelist  [WRBQualifierValue](https://inspire.ec.europa.eu/codelist/WRBQualifierValue) has been solved, now the table with available items is visible. 
Please confirm that everything is correct and if you have any questions please do not hesitate to contact us.

Regards

Arantza
